apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: sandbox-nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sandbox-nginx.prod.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: sandbox-nginx.prod.local