apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langfuse
spec:
  interval: 5m
  timeout: 15m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: charts/sandbox-langfuse
      version: "0.2.0"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  values:
    langfuse:
      postgresql:
        deploy: false
        host: langfuse-postgres-primary
        auth:
          username: langfuse
          database: langfuse
          existingSecret: langfuse-postgres-pguser-langfuse
          secretKeys:
            userPasswordKey: password