apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pvc-usage-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/pvc-usage-exporter
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  values:
    pvcs:
      - name: clickhouse-storage-volume-langfuse-clickhouse-0-0-0
        claimName: clickhouse-storage-volume-langfuse-clickhouse-0-0-0
      - name: clickhouse-storage-volume-langfuse-keeper-0-0
        claimName: clickhouse-storage-volume-langfuse-keeper-0-0
      - name: langfuse-postgres-instance1-vg5g-pgdata
        claimName: langfuse-postgres-instance1-vg5g-pgdata
      - name: langfuse-postgres-repo1
        claimName: langfuse-postgres-repo1
      - name: langfuse-redis
        claimName: langfuse-redis
      - name: langfuse-s3-all-in-one-data
        claimName: langfuse-s3-all-in-one-data