apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pvc-usage-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/pvc-usage-exporter
      version: "0.1.3"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  values:
    pvcSelectors:
      - matchLabels:
          app: langfuse-clickhouse
      - matchLabels:
          app: langfuse-keeper
      - matchLabels:
          postgres-operator.crunchydata.com/cluster: langfuse-postgres
          postgres-operator.crunchydata.com/instance-set: instance1
          postgres-operator.crunchydata.com/role: pgdata
      - matchLabels:
          postgres-operator.crunchydata.com/cluster: langfuse-postgres
          postgres-operator.crunchydata.com/data: pgbackrest
      - matchLabels:
          app.kubernetes.io/name: redis
      - matchLabels:
          app.kubernetes.io/component: seaweedfs-all-in-one