apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: langfuse-postgres
spec:
  postgresVersion: 16
  databaseInitSQL:
    name: langfuse-postgres-init
    key: init.sql
  users:
    - name: langfuse
      databases:
        - langfuse
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi