apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sandbox-app
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sandbox-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system