apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pvc-usage-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/pvc-usage-exporter
      version: "0.1.1"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  values:
    pvcs:
      - name: sandbox-vllm-model-cache
        claimName: sandbox-vllm-model-cache