apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minikube-__ENV__
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: minikube-postgres-operator
    - name: minikube-llm
    - name: minikube-monitoring
    - name: sandbox-env-values-__ENV__
  path: ./clusters/minikube/environments/__ENV__
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: sandbox-nginx
      namespace: __ENV__
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: sandbox-redis
      namespace: __ENV__
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: sandbox-ai-consumer
      namespace: __ENV__
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      cluster: minikube
      environment: __ENV__
