apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minikube-langfuse-namespace
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster-components/langfuse-namespace
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system