apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minikube-llm
  namespace: flux-system
spec:
  dependsOn:
    - name: minikube-postgres-operator
    - name: minikube-cert-manager-issuers
    - name: minikube-monitoring
  interval: 10m
  path: ./cluster-components/llm/overlays/tiny
  prune: true
  wait: true
  timeout: 25m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      cluster: minikube
      environment: llm
