apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sandbox-cluster-config
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/RobertKustra/sandbox-cluster-config.git
  ref:
    branch: development
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sandbox-cluster-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: sandbox-cluster-config
