apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
secretGenerator:
  - name: sandbox-redis-auth
    literals:
      - sandbox-redis-password=prod-change-me
generatorOptions:
  disableNameSuffixHash: true