apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    config:
      clients:
        # The URL of the Loki instance to which Promtail will send logs. This should match the service name and port of the Loki deployment in your cluster.
        - url: http://loki-stack:3100/loki/api/v1/push
