apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: sandbox-vllm
    patch: |-
      - op: replace
        path: /spec/values/image
        value:
          repository: vllm/vllm-openai
          tag: nightly
          pullPolicy: Always
      - op: replace
        path: /spec/values/model/args
        value:
          - Qwen/Qwen2.5-Coder-3B-Instruct
          - --host
          - 0.0.0.0
          - --port
          - "8000"
          - --dtype
          - half
          - --max-model-len
          - "4096"
          - --max-num-seqs
          - "4"
          - --gpu-memory-utilization
          - "0.85"
          - --enforce-eager
          - --served-model-name
          - ziutek_2.0
      - op: replace
        path: /spec/values/resources/requests
        value:
          cpu: "500m"
          memory: 3Gi
      - op: replace
        path: /spec/values/resources/limits
        value:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: 1