apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: platform
    patch: |-
      - op: replace
        path: /metadata/name
        value: postgres-operator
      - op: add
        path: /metadata/annotations/sandbox.local~1description
        value: PostgreSQL operator