apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
resources:
  - ./sandbox-vllm.yaml
  - ./sandbox-vllm-ingress.yaml
secretGenerator:
  - name: hf-token
    literals:
      - HF_TOKEN=dev-change-me
generatorOptions:
  disableNameSuffixHash: true