apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: sandbox-postgres
spec:
  postgresVersion: 16
  users:
    - name: sandbox-app
      databases:
        - sandbox_app
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        storageClassName: csi-hostpath-sc
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
      repos:
        - name: repo1
          schedules:
            full: "0 2 * * 0"
            incremental: "0 2 * * 1-6"
          volume:
            volumeClaimSpec:
              storageClassName: csi-hostpath-sc
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi