apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sandbox-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sandbox-nginx
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sandbox-nginx-values-base
    - kind: ConfigMap
      name: sandbox-nginx-values-env
