apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: sandbox-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sandbox-nginx.local
      secretName: sandbox-nginx-tls
  rules:
    - host: sandbox-nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox-nginx
                port:
                  number: 80
