apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sandbox-app
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: sandbox-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: sandbox-helm-charts
        namespace: flux-system
  valuesFrom:
    - kind: GitRepository
      name: sandbox-env-values
      namespace: flux-system
      path: ./dev/sandbox-app.yaml
# This HelmRelease is isolated to the dev environment.
