apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../namespaces/dev
  - ../../../../namespaces/test
  - ../../../../namespaces/prod
  - ../../../../namespaces/llm
  - ../../../../namespaces/monitoring
