apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./image-reflector.yaml
  - ../../../../apps/sandbox-nginx/overlays/dev
  - ../../../../apps/sandbox-redis/overlays/dev
  - ../../../../postgres/overlays/dev
  - ../../../../apps/sandbox-ai-consumer/overlays/dev
