apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources
  - ./flux-system
  - ./environments/operators-postgres.yaml
  - ./environments/monitoring.yaml
  - ./environments/llm.yaml
  - ./environments/dev.yaml
  # - ./environments/test.yaml
  # - ./environments/prod.yaml
