apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources
  - ./flux-system
  ## Core modules for kubernetes cluster
  - ../../cluster-components/namespaces.yaml
  - ../../cluster-components/operators-postgres.yaml
  - ../../cluster-components/cert-manager.yaml
  - ../../cluster-components/cert-manager-issuers.yaml
  - ../../cluster-components/traefik.yaml
  - ../../cluster-components/monitoring.yaml
  - ../../cluster-components/llm.yaml
  ## Environments for different stages
  - ./environments/dev.yaml
  - ./environments/test.yaml
  - ./environments/prod.yaml
