apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../namespaces/prod
  - ../../../../apps/sandbox-ai-consumer/overlays/prod
  - ../../../../apps/sandbox-nginx/overlays/prod
  - ../../../../apps/sandbox-redis/overlays/prod
  - ../../../../postgres/overlays/prod
