apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-alert-rules
  values:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: web
        scheme: http
    server:
      service:
        type: ClusterIP
      persistentVolume:
        enabled: true
        size: 8Gi
        storageClass: "standard"