apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: clickhouse-operator
    namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3